from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

markup_start = InlineKeyboardMarkup()
b1 = InlineKeyboardButton('New Promo', callback_data='new_promo')
b2 = InlineKeyboardButton('Edit', callback_data='edit')
b3 = InlineKeyboardButton('Delete', callback_data='delete')
b4 = InlineKeyboardButton('Send', callback_data='send')
b5 = InlineKeyboardButton('Export', callback_data='export')
b6 = InlineKeyboardButton('Show', callback_data='show')
markup_start.add(b1)
markup_start.row(b2, b3)
markup_start.row(b4, b5)

markup_edit = InlineKeyboardMarkup()
b1 = InlineKeyboardButton('Name', callback_data='ch_name')
b2 = InlineKeyboardButton('Promo', callback_data='ch_promo')
b3 = InlineKeyboardButton('Expire', callback_data='ch_expire')
b4 = InlineKeyboardButton('Terms', callback_data='ch_terms')
b5 = InlineKeyboardButton('Limit', callback_data='ch_limit')
b6 = InlineKeyboardButton('Time', callback_data='ch_time')
b7 = InlineKeyboardButton('Code', callback_data='ch_code')
b8 = InlineKeyboardButton('<< Back', callback_data='back')
markup_edit.row(b1, b2)
markup_edit.row(b3, b4)
markup_edit.row(b5, b6)
markup_edit.add(b7)
markup_edit.add(b5)